Bugfixes and tests (#19)
* Trigger build

* Export flavor

* Fix ./export

* improved automatic testing with dockerdb

* fixed utf8 problem

* Prevent early exit with `|| true`

* Add python requirements file and install dependencies in virtual env

* Exit with 1 if some test failed

* Fix RETURN_CODE: unbound variable

* Add some debugging output

* Change python shebang to /usr/bin/env python2.7

* Fix "OSError: [Errno 2] No such file or directory"

ERROR: setUpClass (__main__.FrequencyAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "generic/performance.py", line 246, in setUpClass
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ERROR: setUpModule (__main__)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "generic/unicode.py", line 98, in setUpModule
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ERROR: test_unicode_umlaute (__main__.PythonUnicode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python/unicode.py", line 27, in test_unicode_umlaute
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

* Disable tests that require R to be available

* Change wording of expected exception in test_import_fails_for_r_script

* Disable lua/unicode tests until unicode.csv / fn2.unicodedata is available

* Disable generic/performance test until missing csvs are available

Test class FrequencyAnalysis in generic/performance.py disabled. Missing files:
freebase-frequency_analysis.csv and freebase-export.csv.

* Revert "Fix "OSError: [Errno 2] No such file or directory""

The actual problem was a missing EXAPLUS environment variable.

* Set EXAPLUS env var in test script

* Fix varies problems with the test script

* Fix Exasol container version to 6.0.10-d1

* Fix enginedb_import: cd to enginedb_small directory

* Disable one test in python/script_import that needs R

* Fix run_locally bug

* Debug: Add call to ldd

* Add ODBC lib folder to LD_LIBRARY_PATH

* set -u problem

* Remove LD_LIBRARY_PATH again but install unixodbc[-dev] packages

* Add ldd output

* Look for odbc

* Link /usr/lib/x86_64-linux-gnu/libodbcinst.so.1 to libodbcinst.so.2

* sudo!

* Move ln -s to travis.yml install

* Update to docker-db:6.0.11-d1

* Remove virtualenv setup

* Add lxml to requirements.txt

* Improve download code

* Add error output

* Fix file paths

* Setup travis matrix. Includes mini and fancyr_60

* Move script back to top level

* Add output to debug MessageBox

* Switch language_definition of mini to actually use mini container

* Fix fancyr_60 testconfig

* Correct bucket fs name: bucketfs1 -> bfsdefault

* improved automatic testing and fixed bugs with singleCall

* improved automatic tests

* changed condition for testing for virtualenv

* added pytz to requirements.txt

* removed drivers directory

* using different port numbers in tests for different flavors

* adapted loading of enginedb for tests to use different ports depending on flavor

* added lxml library to requirements.txt

* unskipped tests in get_connection.py

* added odbc.ini to .gitignore

* changed travis config

* changed extract_dir when building, skipping some tests when running in travis

* using bash for build script instead of sh

* more flavors in travis

* reenabled unoptimized build for one java file that needs it, removed fancyr_60 from travis -- job takes too long, added pycurl to python3

* removed file test_emul

* added short info about running automated tests for flavors

* disabled some r tests for automatic execution in travis environment

* fixed bug with crashing get_connection

* added new test file for basic tensorflow

* changed back swig version for standard container due to incompatibility with R

* added generic test for get_connection

* reorganized test scripts and travis tests

* adjustment of dockerdb for travis environment

* experimental adjustment of dockerdb for travis environment

* created new flavor standard_60 for the EXASOL 6.0.x version of the standard container

* rename flavors/standard to flavors/standard_61

* rename flavors/standard to flavors/standard_61

* added missing dockerfiles for flavor standard_61

* fixed bugs in singleCall and added more tests

* added file